/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digitalfoodordering;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AddFoodItem extends javax.swing.JFrame {

    /**
     * Creates new form AddFoodItem
     */
    public AddFoodItem() {
        initComponents();
        setSize(1000,1000);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbcuisine = new javax.swing.JComboBox<>();
        cbcategory = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfdesc = new javax.swing.JTextArea();
        tfitemname = new javax.swing.JTextField();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        tfprice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ADD FOOD ITEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 10, 210, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("CUISINE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 70, 30);

        jLabel3.setText("FOOD CATEGORY");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 90, 30);

        jLabel4.setText("ITEM NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 140, 70, 30);

        jLabel5.setText("DESCRIPTION");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 190, 80, 30);

        jLabel6.setText("FOOD TYPE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 280, 70, 30);

        jLabel7.setText("PRICE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 350, 50, 20);

        cbcuisine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----SELECT-----", "SOUTH INDIAN", "PUNJABI", "ITALIAN", "CHINESE", " " }));
        cbcuisine.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbcuisineItemStateChanged(evt);
            }
        });
        cbcuisine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcuisineActionPerformed(evt);
            }
        });
        getContentPane().add(cbcuisine);
        cbcuisine.setBounds(150, 60, 340, 30);

        getContentPane().add(cbcategory);
        cbcategory.setBounds(150, 100, 340, 30);

        tfdesc.setColumns(20);
        tfdesc.setRows(5);
        jScrollPane1.setViewportView(tfdesc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 180, 340, 80);
        getContentPane().add(tfitemname);
        tfitemname.setBounds(150, 140, 340, 30);

        buttonGroup6.add(rb1);
        rb1.setSelected(true);
        rb1.setText("Veg");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rb1);
        rb1.setBounds(160, 293, 80, 20);

        buttonGroup6.add(rb2);
        rb2.setText("Non-Veg");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rb2);
        rb2.setBounds(320, 290, 93, 23);
        getContentPane().add(tfprice);
        tfprice.setBounds(110, 350, 100, 50);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(430, 300, 150, 100);

        jButton1.setText("BROWSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 350, 130, 50);

        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 430, 180, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbcuisineItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbcuisineItemStateChanged
        // TODO add your handling code here:
        String s = cbcuisine.getSelectedItem().toString();
    }//GEN-LAST:event_cbcuisineItemStateChanged

    private void cbcuisineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcuisineActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String cuisine = cbcuisine.getSelectedItem().toString();
            HttpResponse<String> res = Unirest.get("http://localhost:80/GetCategoryByCuisine")
                    .queryString("cuisine", cuisine).asString();
            String response = res.getBody();
            StringTokenizer st = new StringTokenizer(response, "~!@");       //Each Row Seperated
            int n = st.countTokens();
            cbcategory.removeAllItems();
            for (int i = 1; i <= n; i++) {                                   //Loop Only For Rows,Columns Fixed=8
                String row = st.nextToken();
                StringTokenizer st2 = new StringTokenizer(row, "#$%");       //Each Column Seperated
                String name = st2.nextToken();
                String desc = st2.nextToken();
                String photo = st2.nextToken();
                cbcategory.addItem(name);
            }

        } catch (UnirestException ex) {
            Logger.getLogger(GetCategoryByCuisine.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_cbcuisineActionPerformed
    File f=null;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String cuisine = cbcuisine.getSelectedItem().toString();
        String category = cbcategory.getSelectedItem().toString();
        String itemname = tfitemname.getText();
        String description = tfdesc.getText();
        String price =tfprice.getText();
        String type = rb1.isSelected() ? "Veg" : "Non-Veg";
       if (cuisine.equals("") || category.equals("") || description.equals("") || itemname.equals("") || price=="" || f == null) {
            JOptionPane.showMessageDialog(this, "ALL FIELDS ARE MANDATORY!!!");
        }
        else 
        {
            try 
            {
                HttpResponse<String> res = Unirest.post("http://localhost:80/AddFoodItem")
                        .queryString("cuisine", cuisine)
                        .queryString("type", type)
                        .queryString("category", category)
                        .queryString("itemname",itemname)
                        .queryString("description", description)
                        .queryString("price", price)
                        .field("photo", f).asString();
                String response = res.getBody();
                if (response.equals("success")) 
                {
                    JOptionPane.showMessageDialog(this, "FOODITEM ADDED SUCCESSFULLY!!!!!");

                } 
                else 
                {
                    JOptionPane.showMessageDialog(this, "FOOD ITEM ALREADY EXISTS!!!");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }                        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser jfc = new JFileChooser("C:\\");

            int ans = jfc.showOpenDialog(this);
            if (ans == JFileChooser.APPROVE_OPTION) 
            {
                f = jfc.getSelectedFile();
                BufferedImage bi = ImageIO.read(f);
                BufferedImage resizedphoto = resize(bi, jLabel8.getWidth(), jLabel8.getHeight());
                jLabel8.setIcon(new ImageIcon(resizedphoto));
            }
        } 
        catch (Exception ex) 
        {
            ex.printStackTrace();
        }
    }                                        
    BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFoodItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFoodItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFoodItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFoodItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFoodItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JComboBox<String> cbcategory;
    private javax.swing.JComboBox<String> cbcuisine;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextArea tfdesc;
    private javax.swing.JTextField tfitemname;
    private javax.swing.JTextField tfprice;
    // End of variables declaration//GEN-END:variables
}
