/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digitalfoodordering;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AdminChangedPassword extends javax.swing.JFrame {

    /**
     * Creates new form AdminChangedPassword
     */
    String uname;
    public AdminChangedPassword() {
        initComponents();
        setSize(500,500);
    }
    public AdminChangedPassword(String username)
    {
        uname=username;
        initComponents();
        jLabel6.setText(uname);
        setSize(500,500);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("ADMIN CHANGE PASSWORD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 14, 180, 30);

        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(34, 70, 70, 14);

        jLabel3.setText("OLD PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 90, 14);

        jLabel4.setText("NEW PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 140, 83, 14);

        jLabel5.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 107, 14);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 60, 60, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(160, 100, 170, 30);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(160, 140, 170, 30);
        getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(160, 180, 170, 30);

        jButton1.setText("CHANGE PASSWORD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 240, 170, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username = jLabel6.getText();
        String oldpassword = jPasswordField1.getText();
        String newpassword = jPasswordField2.getText();
        String confirmpassword = jPasswordField3.getText();
        if(oldpassword.equals("") || newpassword.equals(""))
        {
            JOptionPane.showMessageDialog(this,"ALL FIELDS ARE COMPULSORY!!");
        }
        else if(newpassword.equals(confirmpassword)==false)
        {
            JOptionPane.showMessageDialog(this,"NEW PASSWORD AND CONFIRM PASSWORD DO NOT MATCH!!!!");
        }
        else 
        {
            try 
            {
                HttpResponse<String> res = Unirest.get("http://localhost:80/AdminChangedPassword").queryString("username",username).queryString("oldpassword",oldpassword).queryString("newpassword", newpassword).queryString("confirmpassword",confirmpassword).asString();
                String response = res.getBody();
                if (response.equals("success")) 
                {
                    JOptionPane.showMessageDialog(this, "PASSWORD CHANGED SUCCESSFUL!!");

                } 
                else 
                {
                    JOptionPane.showMessageDialog(this, "PASSWORD CHANGE FAILED!!");

                }
            } 
            catch (Exception ex) 
            {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminChangedPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminChangedPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminChangedPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminChangedPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminChangedPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    // End of variables declaration//GEN-END:variables

}
